name: CMake on a single platform

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  BUILD_PRESET: cicd

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: "3.29"
          # actions-cache-folder: "cmake-cache"

      - name: Install Linux dependencies
        run: sudo apt-get update && sudo apt-get install -y --fix-missing xorg-dev libglu1-mesa-dev

      - name: Setup Ninja
        uses: ashutoshvarma/setup-ninja@master
        with:
          # ninja version to download. Default: 1.10.0
          version: 1.10.0
          # actions-cache-folder: "ninja-cache"

      - name: Run CMake Workflow
        run: cmake --workflow --preset=${{env.BUILD_PRESET}}
